- commons/src/main/java/com/expedia/www/haystack/pipes/commons/Configuration.java
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ExternalKafkaConfig.java
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ExternalKafkaConfigurationProvider.java
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ExternalKafkaConfigurationProviderTest.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
- kafka-producer/src/test/resources/base.yaml
from the producer's send() to Kafka.
Make all configurations for ExternalKafkaConfig lower case only so that
they can be overridden by environment variables.
> Add a configuration to control whether or not to wait for the response

- json-transformer/pom.xml
- kafka-producer/pom.xml
POMs no longer inherit from the SpringBoot plan.
> Add spring-boot-maven-plug mainClass attribute, needed because the child

- json-transformer/pom.xml
- kafka-producer/pom.xml
Instructions came from https://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/html/build-tool-plugins-maven-plugin.html#build-tool-plugins-maven-packaging-optional-params
Verified that after building MANIFEST.MV contained Start-Class line.
> Add repackage goal to spring-boot-maven-plugin.

- json-transformer/pom.xml
- json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformer.java
- json-transformer/src/main/resources/logback.xml
- json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformerTest.java
- pom.xml
Metrics now starts its own polling, no need to do so in the app.
> Add and use the logback custom appender in json transformer.

- commons/src/main/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSource.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSourceTest.java
- json-transformer/src/main/resources/logback.xml
- kafka-producer/pom.xml
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProtobufToKafkaProducer.java
- kafka-producer/src/main/resources/logback.xml
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProtobufToKafkaProducerTest.java
don't start the metrics polling thread, use custom logback appender.
Also don't remove upper case environment variable after converting
to lower case. This will more easily allow systems that use
haystack-style configurations (lower case, period-delimited) to coexist
in the same JVM with those that use the environment variables directly
(like the logback configurations).
> Apply custom appender changes to haystack-pipes-kafka-producer:

- kafka-producer/build/docker/jmxtrans-agent.xml
- kafka-producer/src/test/resources/static/index.html
"kafka-producer" when creating the kafka-producer application.
> Fix two copy/paste errors in which "json-transfomer" was not replaced by

- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
from the service, because the stack trace itself with the associated
detail is not showing up in Kibana, and include the JSON that was
in the post).
> Improve error message when post to Kafka fails (include the message

- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/TestConstantsAndCommonCode.java
explicit String.format() for the debug message because the combination
of log4j2 and slf4j appears to not call String.format() correctly.
> Add what I thought was an unnecessary null check; bring back the

- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaCallback.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaCallbackTest.java
https://trello.com/c/h3OUDoAY/166-add-async-callback-to-kafka-producer-send-to-look-for-errors.
This is the first of three commits to fully implement the requested
feature in a performant way.
> Add AddProduceIntoExternalKafkaCallback class; see

- commons/src/main/java/com/expedia/www/haystack/pipes/commons/CommonConstants.java
- commons/src/main/java/com/expedia/www/haystack/pipes/commons/Configuration.java
- commons/src/main/java/com/expedia/www/haystack/pipes/commons/Metrics.java
- commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaConfigurationProvider.java
- commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamBuilder.java
- commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamStarter.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSourceTest.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/ConfigurationTest.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/MetricsTest.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaConfigurationProviderTest.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamStarterTest.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/serialization/SerializerDeserializerBaseTest.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/serialization/SpanSerdeFactoryTest.java
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaCallback.java
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProtobufToKafkaProducer.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaCallbackTest.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProtobufToKafkaProducerTest.java
Add some copyright notices to Java source files where they were missing.
Fix some warnings (class/constructor visibility, unused imports).
> Make AddProduceIntoExternalKafkaCallback a static singleton.

- commons/src/main/java/com/expedia/www/haystack/pipes/commons/serialization/SerializerDeserializerBase.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/serialization/SerializerDeserializerBaseTest.java
- json-transformer/src/main/resources/base.yaml
- kafka-producer/ReleaseNotes.md
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
- kafka-producer/src/main/resources/base.yaml
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
- pom.xml
instead. This applies to all metrics in Kafka Producer, but JSON
Transformer's ERROR metric continues to be produced as rates for the
time being.
> Don't send Kafka Producer REQUEST as a rate; send it as a straight count

- pom.xml
that emits a start up metric for the error counter, to help create the
dashboard.
> Upgrade haystack-logback-custom-appender to 0.1.6, to pick up the change

- pom.xml
that emits a heartbeat metric for the error counter, to help create the
dashboard.
> Upgrade haystack-logback-custom-appender to 0.1.7, to pick up the change

- pom.xml
that correctly shuts down the background threads when the custom
appender stops.
> Upgrade haystack-logback-custom-appender to 0.1.8, to pick up the change

- pom.xml
that includes the subsystem as part of the fully qualified class name.
> Upgrade haystack-logback-custom-appender to 0.1.9, to pick up the change

- kafka-producer/pom.xml
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaCallback.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaCallbackTest.java
- pom.xml
callback) so that another change can be made in which the callback
contains a ProducerRecord, permitting retry in the callback.
> Use object pool to provide the callback (instead of using a static

- pom.xml
I believe this was preventing pipes from working because of a changed API in haystack-metrics
> Upgrade haystack metrics to 0.5.0

- kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
- kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
that its value is sometimes negative because it was a ResettingCounter.
> POSTS_IN_FLIGHT counter should be a BasicCounter; I saw on the dashboard

- commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamStarter.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamStarterTest.java
> Log Kafka topics at start up, to help determine if pipes is pointing

- http-poster/pom.xml
- http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostAction.java
- http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/SpringConfig.java
- http-poster/src/main/resources/base.yaml
- http-poster/src/main/resources/log4j2.yaml
- http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostActionTest.java
- http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProviderTest.java
- http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/SpringConfigTest.java
- http-poster/src/test/resources/base.yaml
- pom.xml
Also upgraded JaCoCo to 8.0 (this appears to have fixed some coverage
calculation problems with catch and finally blocks). Brought in
mockserver-netty to start a local HTTP server in some unit tests, which
made writing tests and achieving 100% coverage easier. Note that
mockserver-netty starts up and shuts down very quickly, so the impact
on build times is not severe.
> Finish implementation and unit tests for http-poster.

- json-transformer/pom.xml
- json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/JsonTransformerIsActiveController.java
- json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformer.java
- json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/SpringConfig.java
- json-transformer/src/main/resources/application.properties
- json-transformer/src/main/resources/logback.xml
- json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/JsonTransformerIsActiveControllerTest.java
- json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformerTest.java
- json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/SpringConfigTest.java
- pom.xml
haystack-logback-metrics-appender, and haystack-log4j-metrics-appender;
doing so allows Logback and Spring to function properly when Logback
decides to "reset" the logging system before it's fully running. (This
is the first time that we've used Logback and Spring together; the
Pipes modules that were already Springified use log4j 2.)
> Springify json-transformer. Upgrade to new versions of haystack-metrics,

- http-poster/src/main/resources/base.yaml
as the "configuration of last resort" and "required configurations"
documentation, for http-poster; it needs these configurations because
it uses Servo counters and timers.
> Add graphite (really InfluxDb) configurations to base.yaml, which serves

- firehose-writer/src/main/resources/log4j2.yaml
- http-poster/src/main/resources/log4j2.yaml
- pom.xml
and haystack-logback-metrics-appender, all to pick up the change in
haystack-metrics to support the environment variable override of
HAYSTACK_GRAPHITE_HOST. Change log4j2.yaml to use
${HAYSTACK_GRAPHITE_HOST}. This should make the custom appender work in
http-poster and firehose-writer.
> Bump the versions of haystack-metrics, haystack-log4j-metrics-appender,

- commons/src/main/java/com/expedia/www/haystack/pipes/commons/SystemExitUncaughtExceptionHandler.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/SystemExitUncaughtExceptionHandlerTest.java
We have observed close() timing out when firehose-writer runs out of
memory; this change should allow the JVM to shut down cleanly when
it runs out of memory and thereby be restarted successfully by k8s.
> Don't close Kafka Streams in the uncaught exception handler.

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseAction.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseActionTest.java
creation when growing the list. Make retry sleep back exponential.
> Initialize record list with its maximum size (500) to avoid garbage

- commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaConfig.java
- commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaConfigurationProvider.java
- commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamStarter.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/ConfigurationTest.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaConfigurationProviderTest.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamStarterTest.java
- commons/src/test/resources/base.yaml
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
- firehose-writer/src/main/resources/base.yaml
- http-poster/src/main/resources/base.yaml
- http-poster/src/test/resources/base.yaml
- json-transformer/src/main/resources/base.yaml
- json-transformer/src/test/resources/base.yaml
- kafka-producer/src/main/resources/base.yaml
- kafka-producer/src/test/resources/base.yaml
keyword to FirehoseCollector.addRecordAndReturnBatch() so that the
singleton object can handle more than one kstream thread.
> Add thread count configuration for Kafka Streams; add synchronized

- commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamBuilderBase.java
- commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamBuilderBaseTest.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/Batch.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessor.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorSupplier.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducer.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/BatchTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollectorTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorSupplierTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducerTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfigTest.java
This permits more efficient CPU utilization for the stateful KStreams beans.
> Use KStreams Producer infrastructure instead of ForeachAction.

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCountersAndTimer.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessor.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorSupplier.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCountersAndTimerTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorSupplierTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorTest.java
Remove synchronized keyword from method now that we're not sharing buffer.
Simplify counters/timer use in Firehose by extending CountersAndTimer.
> Count exceptions in Fireshose to learn if we're being throttled.

- secret-detector/src/main/resources/logback.xml
Stream process" message when KafkaStreams.start() is called.
> Set KafkaStreams class's log level to INFO, to see a "Started Kafks

- commons/src/main/java/com/expedia/www/haystack/pipes/commons/test/TestConstantsAndCommonCode.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/HaystackCompositeCreditCardFinder.java
- secret-detector/src/main/resources/finders_default.xml
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorTest.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/HaystackCompositeCreditCardFinderTest.java
CompositeCreditCardFinder provided by chlorine-finder was producing
false positives.
> Add a HaystackCompositeCreditCardFinder class; the

- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/Detector.java
- secret-detector/src/main/resources/finders_default.xml
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorTest.java
Also rename the IP finder to a shorter name to make grafana graphs more readable.
> Log when phone number secrets are found, to help debug false positives.

- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/actions/HaystackPhoneNumberFinder.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/actions/HaystackPhoneNumberFinderTest.java
libphonenumber package just throws them away, leaving the numbers,
resulting in false positives.
> Explicitly check for alphabetic characters in phone number, as the

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfigTest.java
- pom.xml
also use that version, to get better support for bucket timer.
> Use haystack-metrics 2.0.0, with the custom logger packages that

- secret-detector/src/test/resources/finders_default.xml
with all detectors active into test resources to keep unit tests passing.
> Only use the credit card finder when deploying. Put finders_default.xml

- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/S3ConfigFetcher.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/actions/EmailerDetectedAction.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/actions/EmailerDetectedActionTest.java
unneeded System.out.println().
> Don't emit error messages if emails are not configured. Remove an

- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/Detector.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/FinderNameAndServiceName.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/S3ConfigFetcher.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfig.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringWiredDetector.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringWiredS3ConfigFetcher.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorTest.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/FinderNameAndServiceNameTest.java
Make FinderNameAndServiceName an outer class. Remove Spring annotations
from Detector and S3ConfigFetcher. Put those Spring annotations on
new classes SpringWiredDetector and SpringWiredS3ConfigFetcher.
> Changes to facilitate moving some more classes to haystack-commons:

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducer.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducerTest.java
> Remove temporary log message now that we know the correct Kafka topic

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/Batch.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseRecordBufferCollector.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseStringBufferCollector.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/BatchTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseRecordBufferCollectorTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseStringBufferCollectorTest.java
into what might be going on. Also separate the "batch full" vs.
"timed out" decision so that the latter can add the buffered data
before sending to AWS.
> Log errors from Firehose at ERROR level instead of WARN to get insight

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/Batch.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/BatchTest.java
error codes and are hoping that the record ID will help Amazon debug
the issue.
> Add record ID to message for failures; we're seeing InternalFailure

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/Batch.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/BatchTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorTest.java
as we have observed that no records are marked for retry in this case,
resulting in missing spans in Athena.
> Retry all records when receiving an InternalFailure error code from AWS,

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfigTest.java
messages into tagged metrics for ingestion by InfluxDb isn't working yet
and changing it is difficult, so for now I'm reverting to BasicTimer.
> Stop using BucketTimer; the template to transform Graphite plain text

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/AsynchronousFirehoseConsumer.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/BlockingQueueEntry.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/Factory.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConsumer.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCountersAndTimer.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseIsActiveController.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessor.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorSupplier.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/RetryCalculator.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/S3Sender.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/ShutdownHook.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
- firehose-writer/src/main/resources/log4j2.yaml
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/AsynchronousFirehoseConsumerTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/BlockingQueueEntryTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FactoryTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConsumerTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseIsActiveControllerTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorSupplierTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessorTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/RetryCalculatorTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/S3SenderTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/ShutdownHookTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfigTest.java
to improve firehose-writer throughput.
> Make PutRecordBatchAsync calls, with a thread pool to handle responses,

- pom.xml
- secret-detector/src/main/resources/finders_default.xml
- secret-detector/src/test/resources/finders_default.xml
"skinny" HaystackPhoneNumberFinder objects (one for each region) to see
if "fat" is faster than "skinny" at prod volume.
> Use the "fat" HaystackCompositePhoneNumberFinder instead of the seven

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseStringBufferCollector.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseStringBufferCollectorTest.java
https://github.com/ExpediaDotCom/haystack-pipes/issues/251
occurred again; decrease the size of the buffer, log an error with the
offending byte array when the error occurs, put a TODO to use a byte
array instead of a StringBuilder
> Prod issue documented in

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseStringBufferCollector.java
https://github.com/ExpediaDotCom/haystack-pipes/issues/251
was written incorrectly; should use {} instead of %d/%s for slfj4
formatting.
> Attempt to get more information from the Prod issue documented in

- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FailedRecordExtractor.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/InternalFailureErrorLogger.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/S3Sender.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
- firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/UnexpectedExceptionLogger.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FailedRecordExtractorTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/InternalFailureErrorLoggerTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/S3SenderTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfigTest.java
- firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/UnexpectedExceptionLoggerTest.java
- http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostAction.java
- http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/InvalidProtocolBufferExceptionLogger.java
- http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/SpringConfig.java
- http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostActionTest.java
- http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/InvalidProtocolBufferExceptionLoggerTest.java
- http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/SpringConfigTest.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfig.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/actions/EmailerDetectedAction.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/actions/EmailerDetectedActionFactory.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/actions/FromAddressExceptionLogger.java
- secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/actions/ToAddressExceptionLogger.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfigTest.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/actions/EmailerDetectedActionMimeMessageFactoryTest.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/actions/EmailerDetectedActionTest.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/actions/FromAddressExceptionLoggerTest.java
- secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/actions/ToAddressExceptionLoggerTest.java
only be one logger.error call in FailedRecordExtractor. This is part of
the fix for https://github.com/ExpediaDotCom/haystack-pipes/issues/265.
> Add FailedRecordExtractor with a logError() method so that there will
