json-transformer/src/main/java/com/expedia/www/haystack/pipes/ChangeEnvVarsToLowerCaseConfigurationSource.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/ProtobufToJsonTransformer.java

to ChangeEnvVarsToLowerCaseConfigurationSource

Rename HaystackEnvironmentVariablesConfigurationSource class

---

json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ChangeEnvVarsToLowerCaseConfigurationSource.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/Constants.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/IntermediateStreamsConfig.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/KafkaConfig.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformer.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/SpanJsonSerializer.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/SpanProtobufDeserializer.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/SystemExitUncaughtExceptionHandler.java
json-transformer/src/main/resources/logback.xml
json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformerTest.java
json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/SpanJsonSerializerTest.java
json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/SpanProtobufDeserializerTest.java
json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/SystemExitUncaughtExceptionHandlerTest.java
json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/TestConstantsAndCommonCode.java

so that additional modules will not conflict package-wise.

Move everything to a jsonTransformer package;

---

commons/pom.xml
commons/src/main/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSource.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/Configuration.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSourceTest.java
json-transformer/pom.xml
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformer.java
kafka-producer/pom.xml
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/JsonToKafkaProducer.java
pom.xml

(kafka-producer will take advantage of the refactoring)

Create commons module, start refactoring into it, create kafka-producer

---

commons/pom.xml
commons/src/main/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSource.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/Configuration.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSourceTest.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/ConfigurationTest.java
commons/src/test/resources/base.yaml
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformer.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/JsonToKafkaProducer.java

to facilitate unit tests by its clients.

More tests for the commons module. Make Configuration class non-static

---

commons/pom.xml
commons/src/main/java/com/expedia/www/haystack/pipes/commons/Configuration.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/KafkaConfigurationProvider.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/KafkaStreamBuilder.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/KafkaStreamStarter.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/ConfigurationTest.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/KafkaConfigurationProviderTest.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/KafkaStreamStarterTest.java
commons/src/test/resources/base.yaml
json-transformer/pom.xml
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/IsActiveController.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformer.java
json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformerTest.java
kafka-producer/pom.xml
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/JsonToKafkaProducer.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
kafka-producer/src/main/resources/base.yaml
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/JsonToKafkaProducerTest.java

Move more Kafka configuration logic into commons.
Add copyright notice where it was missing.

More refactoring: Move shared Kafka stream starting into commons.

---

commons/src/main/java/com/expedia/www/haystack/pipes/commons/serialization/SpanProtobufDeserializer.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/serialization/SpanJsonSerializerTest.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/serialization/SpanProtobufDeserializerTest.java

https://github.com/jacoco/jacoco/issues/88

Improve JaCoCo code coverage for finally blocks: see

---

commons/pom.xml
commons/src/main/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSource.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/serialization/SerializerDeserializerBase.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/serialization/SpanJsonSerializer.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/serialization/SpanProtobufDeserializer.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/ChangeEnvVarsToLowerCaseConfigurationSourceTest.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/serialization/SerializerDeserializerBaseTest.java
json-transformer/pom.xml
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformer.java
json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformerTest.java
kafka-producer/pom.xml
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java

Boo-yah. Doing so also led to the discovery (and fixing) of unnecessary
serialization in ProtobufToJsonTransformer.buildStreamTopology().

Achieve, and require for the build to succeed, 100% unit test coverage.

---

commons/pom.xml
json-transformer/pom.xml
kafka-producer/pom.xml
pom.xml

Change haystack-metrics version to 0.2.1 to pick up all configs in

---

kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java

is not visible in Kibana. Also use the smarter var args slf4j debug().

Include line number when logging posting exception, as the stack trace

---

commons/src/test/java/com/expedia/www/haystack/pipes/commons/ConfigurationTest.java
commons/src/test/resources/base.yaml
json-transformer/ReleaseNotes.md
json-transformer/build/docker/jmxtrans-agent.xml
json-transformer/src/main/resources/base.yaml
json-transformer/src/main/resources/logback.xml
kafka-producer/ReleaseNotes.md
kafka-producer/build/docker/jmxtrans-agent.xml
kafka-producer/src/main/resources/base.yaml
kafka-producer/src/main/resources/logback.xml
kafka-producer/src/test/resources/base.yaml
pom.xml

Deployments will probably failed until the k8s scripts are updated.

Change configuration haystack.graphite.address to haystack.graphite.host

---

kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ExternalKafkaConfig.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ExternalKafkaConfigurationProvider.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
kafka-producer/src/main/resources/base.yaml
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ExternalKafkaConfigurationProviderTest.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
kafka-producer/src/test/resources/base.yaml

because the code always waits for responses in the background.

Remove with "wait for response" boolean; this is no longer necessary

---

pom.xml

ERROR_COUNT (InfluxDb template change needed next)

Upgrade the custom appender to 0.1.10 so that subsystem comes in the

---

pom.xml

of the variable in pom.xml to make its purpose clearer.

Upgrade Spring boot plugins version to 1.5.9.RELEASE, changing the name

---

firehose-writer/pom.xml
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
firehose-writer/src/spring-config.xml
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollectorTest.java
pom.xml

empty spring-config.xml (I'm going to inject dependencies with Spring).

Beginnings of FirehoseWriter: new module, new FirehoseCollector class,

---

kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ExternalKafkaConfigurationProviderTest.java
kafka-producer/src/test/resources/base.yaml

Port was already in external broker list; don't add it when creating

---

firehose-writer/pom.xml
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/Constants.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseAction.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseIsActiveController.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducer.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
firehose-writer/src/main/resources/application.properties
firehose-writer/src/main/resources/base.yaml
firehose-writer/src/main/resources/static/index.html
firehose-writer/src/spring-config.xml
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseActionTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseIsActiveControllerTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducerTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfigTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/TestConstantsAndCommonCode.java
pom.xml

Beginnings of Spring configuration: the ping app works, with Spring-

---

commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/TagFlattener.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/TestConstantsAndCommonCode.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/TagFlattenerTest.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
kafka-producer/src/main/resources/base.yaml
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/TestConstantsAndCommonCode.java
pom.xml

Also downgrade Spring to 4.3.13 to match what spring-boot expects.
Also put port in external Kafka URL in configuration.

Move tag flattening code to commons so http-poster can use it.

---

firehose-writer/pom.xml
http-poster/pom.xml
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/ContentCollector.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfig.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProvider.java
http-poster/src/main/resources/base.yaml
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/ContentCollectorTest.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProviderTest.java
kafka-producer/pom.xml

Add configuration (maximum allowed bytes per post, < 1M per Doppler

---

firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollectorTest.java
http-poster/pom.xml
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/ContentCollector.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/ContentCollectorTest.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProviderTest.java
http-poster/src/test/resources/base.yaml
pom.xml

Also added a missing test in firehose-writer.

Flesh out ContentCollector in http-poster.

---

http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/ContentCollector.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfig.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProvider.java
http-poster/src/main/resources/base.yaml
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/ContentCollectorTest.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProviderTest.java
http-poster/src/test/resources/base.yaml

make it easier to tailor the POST body in the Doppler multlines format.

Add more configurations for the HTTP POST; these new configurations

---

http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostAction.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfig.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProvider.java
http-poster/src/main/resources/base.yaml
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostActionTest.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProviderTest.java
http-poster/src/test/resources/base.yaml

Call setDoOutput(true) on the connection so that it can be written to.

Collapse the "endpoint" and "url" configurations into just "url";

---

commons/src/main/java/com/expedia/www/haystack/pipes/commons/CommonConstants.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/Configuration.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/TagFlattener.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/test/TestConstantsAndCommonCode.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/TagFlattenerTest.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseAction.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfig.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfigurationProvider.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
firehose-writer/src/main/resources/base.yaml
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseActionTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfigurationProviderTest.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostAction.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostActionTest.java

1) Add a new line to the end of the JSON to make Firehose happy.
2) Make TestConstantsAndCommonCode in commons an interface.
3) Refactor some constants, create some new constants.
4) More work on FirehoseAction.apply().
5) New Firehose configuration classes and values in yaml files.
6) More Spring beans to support the above.

More work on firehose-writer:

---

firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/Batch.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/Counters.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseAction.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollector.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfig.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfigurationProvider.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
firehose-writer/src/main/resources/log4j2.yaml
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/BatchTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/CountersTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseActionTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseCollectorTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfigurationProviderTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfigTest.java
http-poster/src/main/resources/log4j2.yaml

trace removal syntax for log4j2.

Finish FirehoseWriter. Add missing copyright notices. Fix the stack

---

kafka-producer/pom.xml
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/CallbackFactory.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/KafkaProducerIsActiveController.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaAction.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaCallback.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProtobufToKafkaProducer.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/SpringConfig.java
kafka-producer/src/main/resources/application.properties
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ExternalKafkaConfigurationProviderTest.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/KafkaProducerIsActiveControllerTest.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaActionTest.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProduceIntoExternalKafkaCallbackTest.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProtobufToKafkaProducerTest.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/SpringConfigTest.java

SpringConfig tests still need to be written.

Springify kafka-producer. Object pool is still static, and some

---

firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseAction.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseActionTest.java

before this fix the exception from Firehose was never logged,
making it difficult to determine root cause.

Log the first exception seen if all retries fail;

---

firehose-writer/src/main/resources/log4j2.yaml
http-poster/src/main/resources/log4j2.yaml

Also attempt to make the replacement of new lines in stack trace better.

Fix the syntax of the log4j2 configuration to include date/time in log.

---

commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/TagFlattener.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/test/TestConstantsAndCommonCode.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/TagFlattenerTest.java

firehose-writer in the Integration environment.

Fix NullPointerException in TagFlattener, seen when running

---

firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseAction.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfig.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfigurationProvider.java
firehose-writer/src/main/resources/base.yaml
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseActionTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseConfigurationProviderTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducerTest.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/ContentCollector.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostAction.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfig.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProvider.java
http-poster/src/main/resources/base.yaml
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/ContentCollectorTest.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostActionTest.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/HttpPostConfigurationProviderTest.java
http-poster/src/test/java/com/expedia/www/haystack/pipes/httpPoster/SpringConfigTest.java
http-poster/src/test/resources/base.yaml

Make all numeric configurations to String so that they can be overridden

---

firehose-writer/src/main/resources/log4j2.yaml
http-poster/src/main/resources/log4j2.yaml
pom.xml

to get more logging at start up.

New versions of haystack-metrics and haystack-log4j-metrics-appender

---

pom.xml

haystack-log4j-metrics-appender, to get proper management of the
metrics polling threads.

New versions of haystack-metrics, haystack-log4j-metrics-appender, and

---

firehose-writer/build/docker/jmxtrans-agent.xml
firehose-writer/src/main/resources/base.yaml
firehose-writer/src/main/resources/log4j2.yaml
http-poster/build/docker/jmxtrans-agent.xml
http-poster/src/main/resources/base.yaml
http-poster/src/main/resources/log4j2.yaml
http-poster/src/test/resources/base.yaml
json-transformer/build/docker/jmxtrans-agent.xml
json-transformer/src/main/resources/base.yaml
json-transformer/src/test/resources/base.yaml
kafka-producer/build/docker/jmxtrans-agent.xml
kafka-producer/src/main/resources/base.yaml
kafka-producer/src/test/resources/base.yaml

metrics. Remove others that aren't meaningful for the app.

Change metrics polling intervals to 5 minutes. Add some more jmxtrans

---

firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseProcessor.java
firehose-writer/src/main/resources/log4j2.yaml

codes from Firehose. Also got rid of an unused import in
FirehoseProcessor and did some inlining; unfortunately this changes the
log line of the metric, but now's the time to make this change while I'm
working on dashboards.

Change the log level for the Batch class to WARN so that we see error

---

commons/src/main/java/com/expedia/www/haystack/pipes/commons/test/TestConstantsAndCommonCode.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/SpringConfig.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/SpringConfigTest.java
pom.xml
secret-detector/Makefile
secret-detector/build/docker/Dockerfile
secret-detector/build/docker/jmxtrans-agent.xml
secret-detector/build/docker/start-app.sh
secret-detector/pom.xml
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/Constants.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/Detector.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/DetectorAction.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/DetectorIsActiveController.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/DetectorProducer.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfig.java
secret-detector/src/main/resources/base.yaml
secret-detector/src/main/resources/logback.xml
secret-detector/src/main/resources/static/index.html
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorActionTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorIsActiveControllerTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorProducerTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfigTest.java
secret-detector/src/test/resources/base.yaml

more work is needed by the application will run.

Initial release of secret-detector module. Just unit tests so far,

---

commons/src/main/java/com/expedia/www/haystack/pipes/commons/test/TestConstantsAndCommonCode.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/Detector.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorTest.java

not in the string representation of the entire span.

Only look for secrets in a Span's tags and the fields of its logs,

---

pom.xml
secret-detector/README.md
secret-detector/pom.xml
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/DetectorAction.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/DetectorIsActiveController.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/Emailer.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SecretsConfig.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SecretsConfigurationProvider.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SenderImpl.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfig.java
secret-detector/src/main/resources/application.properties
secret-detector/src/main/resources/base.yaml
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorActionTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/EmailerTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/SecretsConfigurationProviderTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfigTest.java
secret-detector/src/test/resources/base.yaml

Still need to create an "notification provider" construct; right now
Emailer is currently the only available choice. Soon there will be an
SNS choice, and a configuration to specify what choices you want.

Finish code necessary for this to run in the Test environment.

---

secret-detector/src/main/resources/base.yaml
secret-detector/src/test/resources/base.yaml

copy/paste error from another application.

Change topic in configuration from json-spans to proto-spans; this was a

---

secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/com/expedia/www/haystack/pipes/secretDetector/actions/NonLocalIpV4AddressFinder.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/com/expedia/www/haystack/pipes/secretDetector/actions/NonLocalIpV4AddressFinderTest.java

not removing false positives that occurred in the middle of a string.

Fix the implemenation of NonLocalIpV4AddressFinder.find(); it was

---

commons/src/main/java/com/expedia/www/haystack/pipes/commons/test/TestConstantsAndCommonCode.java
secret-detector/src/main/resources/finders_default.xml
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorTest.java

finders_default.xml file whose NonLocalIpV4AddressFinder was just
commented out.

Fix the unit tests, by removing a unit test that was using the

---

secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/actions/HaystackPhoneNumberFinder.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/actions/NonLocalIpV4AddressFinder.java
secret-detector/src/main/resources/base.yaml
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/actions/HaystackPhoneNumberFinderTest.java

Also increase the number of Kafka threads to 4.

Make the phone number checker ignore strings that are IP addresses.

---

pom.xml
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/Detector.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorTest.java

Use haystack-metrics 1.0. Stop logging when a secret is found, except

---

secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/DetectorAction.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/S3ConfigFetcher.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/DetectorActionTest.java

out why the whitelist isn't working.

Temporary change to log more about whitelist activity, trying to figure

---

secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/S3ConfigFetcher.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/S3ConfigFetcherTest.java

the "is it time to update" code.

Fix the whitelist problem by forcing all whitelist checks to go through

---

secret-detector/src/main/resources/finders_default.xml

Turn on all secret detectors; in the past few weeks, only credit card

---

pom.xml
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfig.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringWiredSpanSecretMasker.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufSpanMaskerToKafkaTransformer.java
secret-detector/src/main/resources/base.yaml
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufSpanMaskerToKafkaTransformerTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufSpanToEmailInKafkaTransformerTest.java
secret-detector/src/test/resources/base.yaml

ProtobufSpanMasterToKafkaTransformer and the beans it requires.

Support masking of secrets: bring in new haystack-commons, write

---

pom.xml

and add a dependency on Guava.

Use haystack-commons 1.0.28 to use Guava for string emptiness detection,

---

commons/src/main/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamBuilderBase.java
commons/src/main/java/com/expedia/www/haystack/pipes/commons/serialization/SerdeFactory.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/kafka/KafkaStreamBuilderBaseTest.java
commons/src/test/java/com/expedia/www/haystack/pipes/commons/serialization/SerdeFactoryTest.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducer.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/ProtobufToFirehoseProducerTest.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/ProtobufToHttpPoster.java
http-poster/src/main/java/com/expedia/www/haystack/pipes/httpPoster/SpringConfig.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformer.java
json-transformer/src/main/java/com/expedia/www/haystack/pipes/jsonTransformer/SpringConfig.java
json-transformer/src/test/java/com/expedia/www/haystack/pipes/jsonTransformer/ProtobufToJsonTransformerTest.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/ProtobufToKafkaProducer.java
kafka-producer/src/main/java/com/expedia/www/haystack/pipes/kafkaProducer/SpringConfig.java
kafka-producer/src/test/java/com/expedia/www/haystack/pipes/kafkaProducer/ProtobufToKafkaProducerTest.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfig.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufSpanMaskerToKafkaTransformer.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufSpanToEmailInKafkaTransformer.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufToDetectorAction.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfigTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufSpanMaskerToKafkaTransformerTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufSpanToEmailInKafkaTransformerTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/mains/ProtobufToDetectorActionTest.java

between source and destination streams.

Kafka Streams Serde objects aren't thread safe, so don't share them

---

pom.xml

dependencies was the removal of logback.xml in the haystack-metrics
src/resources directory.)

Upgrade versions of some dependencies. (The interesting change in those

---

pom.xml

secret-detector to detect phone numbers from all G7 countries.

Use a new version of haystack-commons to pick up the change that allows

---

pom.xml
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfig.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringWiredDetector.java
secret-detector/src/main/java/com/expedia/www/haystack/pipes/secretDetector/SpringWiredSpanSecretMasker.java
secret-detector/src/main/resources/finders_default.xml
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/SpringConfigTest.java
secret-detector/src/test/java/com/expedia/www/haystack/pipes/secretDetector/SpringWiredSpanSecretMaskerTest.java

finders_default.xml gets parsed properly.

Use HaystackFinderEngine instead of FinderEngine everywhere, so that

---

pom.xml

that stop after finding a secret

Use haystack-secrets-commons 1.0.5 to get "short-circuiting" finders

---

secret-detector/src/main/resources/finders_default.xml

finds the most secrets. This should help performance.

Move the IP V4 finder to the top of default_finders.xml, since it is

---

firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseStringBufferCollectorTest.java

documented in https://github.com/ExpediaDotCom/haystack-pipes/issues/251

Added unit test trying (unsuccessfully) to recreate the Prod issue

---

firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseByteArrayCollector.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseStringBufferCollector.java
firehose-writer/src/main/java/com/expedia/www/haystack/pipes/firehoseWriter/SpringConfig.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseByteArrayCollectorTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/FirehoseStringBufferCollectorTest.java
firehose-writer/src/test/java/com/expedia/www/haystack/pipes/firehoseWriter/SimpleSpringConfigTest.java

See https://github.com/ExpediaDotCom/haystack-pipes/issues/251

Use byte array in collector

---

firehose-writer/build/docker/jmxtrans-agent.xml
http-poster/build/docker/jmxtrans-agent.xml
json-transformer/build/docker/jmxtrans-agent.xml
kafka-producer/build/docker/jmxtrans-agent.xml
secret-detector/build/docker/jmxtrans-agent.xml

see https://github.com/ExpediaDotCom/haystack-pipes/issues/258

Reduce number of metrics sent to InfluxDb;

---

pom.xml

see https://github.com/ExpediaDotCom/haystack-pipes/issues/260.

Fix security vulnerability:
